BrutalBosses = в коде мода исправил ошибку обращения к null
```
[22:28:21] [Render thread/ERROR] [minecraft/BlockableEventLoop]: Error executing task on Client
java.lang.NullPointerException: Cannot invoke "com.brutalbosses.entity.BossType.setBossBar(boolean)" because "this.bossEntry" is null
	at com.brutalbosses.entity.capability.BossCapability.deserializeNBT(BossCapability.java:140)
```